language: node_js
node_js:
- '5.10'

addons:
  firefox: '42.0'

sudo: true

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
        --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 2560x1440x16

before_script:
    - wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh
    - npm run dev &
    - npm install -g nightwatch
