language: node_js
node_js:
- '5.10'

addons:
  firefox: '42.0'
  hosts:
    - www.birdervsbirder.com

env:
  global:
    - NODE_ENV=development

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
        --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 2560x1440x16

before_script:
    - npm install -g nightwatch
    - npm run start-debug &
    - sleep 10
    - ping -c 1 http://www.birdervsbirder.com:5000
    - curl http:///www.birdervsbirder.com:5000